version: '2'
services:
  nginx:
    build: requirements/nginx
    image: i-nginx
    ports:
      - 443:443
    container_name: nginx
    networks:
     - inception
    volumes:
     - wordpress:/var/www/html/
    depends_on:
      - wordpress
    restart: always
  wordpress:
    build: requirements/wordpress
    image: i-wordpress
    container_name: wordpress
    networks:
     - inception
    depends_on:
     - mariadb
    env_file:
      - .env
    volumes:
     - wordpress:/var/www/html/
    restart: on-failure
  mariadb:
    build: requirements/mariadb
    image: i-mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql
    restart: on-failure
networks:
  inception:
     driver: bridge
volumes:
  db:
    driver: local
    driver_opts:
        type: none
        device: ../data/mariadb
        o: bind
  wordpress:
    driver: local
    driver_opts:
        type: none
        device: ../data/wordpress
        o: bind
